################################
### Configuration Parameters ###
################################
epochs: 20
in_sample: "datasets/data_combined.pkl"
out_path: "output/results"
embed_dim: 16
num_heads: 4
latent_dim: 32
learning_rate: 0.0001
lr_step_size: 12
lr_step_gamma: 0.1
eval_model: "output/results/model_final.torch"
